### ISSUE TITLE
Getting an login error

### ISSUE THREAD

**Issue by jagalindo** [trocotronic/edistribucion#1]
I've tried to use the script Sadly I do not have much python knowledge by the moment. 

In the example, after updating user and password I always get as response:

EdistribucionAPI.EdisError: Unexpected error in loginForm. Cannot continue. The raw log is below:

I'm running this on an Arch installation with python3.8
'''
[21/08/2020 13:40:58] [INFO] Performing login routine
[21/08/2020 13:40:58] [DEBUG] https://zonaprivada.edistribucion.com:443 "POST /areaprivada/s/sfsites/aura?other.LightningLoginForm.login=1 HTTP/1.1" 200 None
[21/08/2020 13:40:58] [INFO] Sending POST request to https://zonaprivada.edistribucion.com/areaprivada/s/sfsites/aura?other.LightningLoginForm.login=1
[21/08/2020 13:40:58] [DEBUG] Parameters: https://zonaprivada.edistribucion.com/areaprivada/s/sfsites/aura?other.LightningLoginForm.login=1
[21/08/2020 13:40:58] [DEBUG] Headers: {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:77.0) Gecko/20100101 Firefox/77.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Cookie': 'renderCtx=%7B%22pageId%22%3A%22ebdf870b-5acd-4526-a912-588b66f15b22%22%2C%22schema%22%3A%22Published%22%2C%22viewType%22%3A%22Published%22%2C%22brandingSetId%22%3A%2219645c47-34b5-4d50-9bc1-4424bb2f3ebe%22%2C%22audienceIds%22%3A%22%22%7D; sfdc-stream=!0Bj4G9jFS/P8Yo03d1xt/fnN1zETUfSEbyRJ6RWnzeYTR0mlBKVrhm1OsS0xPj/TC0ZHMn5XvR1Utco=', 'Content-Length': '803', 'Content-Type': 'application/x-www-form-urlencoded'}
[21/08/2020 13:40:58] [INFO] Response with code: 200
[21/08/2020 13:40:58] [DEBUG] Headers: {'Date': 'Fri, 21 Aug 2020 11:41:00 GMT', 'X-B3-TraceId': '11f69591cdb95917', 'X-B3-SpanId': '11f69591cdb95917', 'X-B3-Sampled': '0', 'Cache-Control': 'no-cache,must-revalidate,max-age=0,no-store,private', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Referrer-Policy': 'origin-when-cross-origin', 'Expires': 'Tue, 07 Jul 2020 11:41:00 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Last-Modified': 'Tue, 07 Jul 2020 11:41:00 GMT', 'Vary': 'Accept-Encoding', 'Content-Encoding': 'gzip', 'Transfer-Encoding': 'chunked'}
[21/08/2020 13:40:58] [DEBUG] History: []
Traceback (most recent call last):
  File "./example.py", line 15, in <module>
    edis.login()
  File "/home/jagalindo/Documentos/Repositories/edistribucion/EdistribucionAPI.py", line 153, in login
    return self.__force_login()
  File "/home/jagalindo/Documentos/Repositories/edistribucion/EdistribucionAPI.py", line 182, in __force_login
    raise EdisError('Unexpected error in loginForm. Cannot continue')
'''

**Comment by trocotronic** [comment]
Hi.

It should be fixed in 23b638ca38cb037a8c494ca18a1b5d211fc94af4

**Comment by jagalindo** [comment]
Thank you a lot. It is working now. I'd see how to integrate this into home assistant
