### ISSUE TITLE
EdistribucionAPI.Edistribucion.EdisError: token not found. Cannot continue

### ISSUE THREAD

**Issue by c1328** [trocotronic/edistribucion#32]
Hello! Since a few days I get the following error:

`[04/11/2023 22:35:21] [INFO] Response with code: 200
[04/11/2023 22:35:21] [INFO] Accessing to landing page
[04/11/2023 22:35:21] [INFO] Sending GET request to https://zonaprivada.edistribucion.com/areaprivada/s/
[04/11/2023 22:35:21] [INFO] Response with code: 200
[04/11/2023 22:35:21] [INFO] Loading token scripts
Traceback (most recent call last):
  File "/usr/local/bin/edistribucion2/example.py", line 11, in <module>
    edis = Edistribucion()
  File "/usr/local/lib/python3.9/dist-packages/EdistribucionAPI/Edistribucion.py", line 133, in __init__
    self.login()
  File "/usr/local/lib/python3.9/dist-packages/EdistribucionAPI/Edistribucion.py", line 240, in login
    return self.__force_login()
  File "/usr/local/lib/python3.9/dist-packages/EdistribucionAPI/Edistribucion.py", line 314, in __force_login
    raise EdisError('token not found. Cannot continue')
EdistribucionAPI.Edistribucion.EdisError: token not found. Cannot continue`

Any ideas? Thanks!

**Comment by c1328** [comment]
Sorry, just recognised https://github.com/trocotronic/edistribucion/issues/27
I'll give it a try but I explicitly did a fresh clone right now.

**Comment by trocotronic** [comment]
You are using an older version, as line `314` does not correspond to this.
Reopen if persists.
