### ISSUE TITLE
error de API

### ISSUE THREAD

**Issue by ghost** [trocotronic/edistribucion#33]
[24/02/2024 21:13:59] [INFO] Response with code: 200
Traceback (most recent call last):
  File "/home/jose/edistribucion/./contador.py", line 15, in <module>
    meter = edis.get_meter(cups)
            ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/EdistribucionAPI/Edistribucion.py", line 395, in get_meter
    return self.__run_action_command(action)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/EdistribucionAPI/Edistribucion.py", line 354, in __run_action_command
    req = self.__command(f"other.{command}=1", post=data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/EdistribucionAPI/Edistribucion.py", line 219, in __command
    if (jr['actions'][0]['state'] != 'SUCCESS'):
        ~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by polhenarejos** [comment]
¿Te funciona la consulta de tu contador a través de la web?

**Comment by bepece1** [comment]
Works again. Thanks
