### ISSUE TITLE
Force Login Error

### ISSUE THREAD

**Issue by gbasile** [trocotronic/edistribucion#4]
First of all, thanks for your project 🙏 

I'm using [the fork](https://github.com/jagalindo/edistribucion) from @jagalindo to integrate your script with my Home Assistant. I receive this error quite often and I was wondering if you were aware of this issue. 

```
Logger: homeassistant.helpers.entity
Source: custom_components/edistribucion/backend/EdistribucionAPI.py:192

Update for sensor.eds_power_consumption fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 482, in async_device_update
    await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/edistribucion/sensor.py", line 51, in update
    meter = edis.get_meter(cups)
  File "/config/custom_components/edistribucion/backend/EdistribucionAPI.py", line 247, in get_meter
    r = self.__command('other.WP_ContadorICP_CTRL.consultarContador=1', post=data)
  File "/config/custom_components/edistribucion/backend/EdistribucionAPI.py", line 134, in __command
    self.__force_login()
  File "/config/custom_components/edistribucion/backend/EdistribucionAPI.py", line 192, in __force_login
    raise EdisError('Unexpected error in loginForm. Cannot continue')
custom_components.edistribucion.backend.EdistribucionAPI.EdisError: Unexpected error in loginForm. Cannot continue
```

**Comment by trocotronic** [comment]
I cannot reproduce this error. Remove `edistribucion.access` and `edistribucion.session` files and try it again.
Otherwise provide the complete debug window.

**Comment by gbasile** [comment]
Sure, gonna give it a try. 
Noob question: Where are these file stored?

**Comment by trocotronic** [comment]
b6533ce fixes lots of session errors. Give it a try
