### ISSUE TITLE
Errores en la página de Endesa?

### ISSUE THREAD

**Issue by alsak0de** [trocotronic/edistribucion#6]
Más de la mitad de las peticiones acaba así: 

Traceback (most recent call last):
  File "/home/albert/edistribucion/example.py", line 19, in <module>
    meter = edis.get_meter(cups)
  File "/NAS/home/albert/edistribucion/EdistribucionAPI.py", line 248, in get_meter
    r = self.__command('other.WP_ContadorICP_CTRL.consultarContador=1', post=data)
  File "/NAS/home/albert/edistribucion/EdistribucionAPI.py", line 135, in __command
    self.__force_login()
  File "/NAS/home/albert/edistribucion/EdistribucionAPI.py", line 193, in __force_login
    raise EdisError('Unexpected error in loginForm. Cannot continue')
EdistribucionAPI.EdisError: Unexpected error in loginForm. Cannot continue

Aunque algunas 'acaban bien' :). Supongo que es culpa de la página, ¿no?

**Comment by trocotronic** [comment]
b6533ce debería de solucionarlo.

**Comment by alsak0de** [comment]
Gracias; enhorabuena por tu contribución. Buen trabajo de scrapping. Lástima que Endesa no nos de un API abierta sencila.
